<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>Routinefy - Analytics</title>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"><link rel="stylesheet" href="style2.css"></head>
<body class="dashboard-body d-flex flex-column min-vh-100">
<header class="dashboard-header bg-white shadow-sm py-3 px-4 d-flex justify-content-between align-items-center"><h1 class="logo m-0 fw-bold fs-3">Routinefy</h1><nav class="nav-links d-flex gap-3 align-items-center"><a href="dashboard.php" class="nav-link text-dark">Dashboard</a><a href="#" class="btn btn-dark btn-sm rounded-pill px-3 active">Analytics</a><a href="#" class="nav-link text-dark" onclick="window.api.logout();return false;">Log out</a></nav></header>
<main class="container my-5 flex-grow-1"><div class="mb-4"><h2 class="fs-4 mb-1" id="welcomeMsg">Welcome User 👋</h2><p class="text-muted mb-0">A clearer view of your consistency, streaks and habit mix.</p></div>
<div class="row g-3 mb-4"><div class="col-md-3"><div class="card border-0 shadow-sm p-4 h-100"><small class="text-muted">ACTIVE HABITS</small><div class="fs-2 fw-bold" id="statTotal">0</div></div></div><div class="col-md-3"><div class="card border-0 shadow-sm p-4 h-100"><small class="text-muted">HIGHEST STREAK</small><div class="fs-2 fw-bold" id="statStreak">0</div><small class="text-muted">days</small></div></div><div class="col-md-3"><div class="card border-0 shadow-sm p-4 h-100"><small class="text-muted">ALL-TIME COMPLETION</small><div class="fs-2 fw-bold" id="statRate">0%</div></div></div><div class="col-md-3"><div class="card border-0 shadow-sm p-4 h-100"><small class="text-muted">LAST 7 DAYS</small><div class="fs-2 fw-bold" id="statWeek">0</div><small class="text-muted">completed check-ins</small></div></div></div>
<div class="row g-4"><div class="col-lg-7"><div class="card border-0 shadow-sm p-4"><h3 class="fs-5 fw-bold">Last 7 Days</h3><canvas id="weeklyChart" height="120"></canvas></div></div><div class="col-lg-5"><div class="card border-0 shadow-sm p-4"><h3 class="fs-5 fw-bold">Habit Categories</h3><canvas id="categoryChart" height="190"></canvas></div></div><div class="col-12"><div class="card border-0 shadow-sm p-4"><h3 class="fs-5 fw-bold">Last 30 Days</h3><canvas id="monthlyChart" height="110"></canvas></div></div></div>
</main><footer class="bg-white text-center py-3 border-top mt-auto shadow-sm"><p class="m-0 text-muted small">&copy; 2026 Routinefy. Built for ICT 1209 Mini Project - Rajarata University of Sri Lanka.</p></footer>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script src="js/api.js"></script><script>
let weeklyChart,monthlyChart,categoryChart;
async function loadAnalytics(){const u=await window.api.requireUserPage();if(!u)return;document.getElementById('welcomeMsg').textContent=`Welcome ${u.full_name} 👋`;const r=await window.api.fetchWithAuth('/analytics');if(!r.ok)return;const d=await r.json();document.getElementById('statTotal').textContent=d.total_habits;document.getElementById('statStreak').textContent=d.highest_streak;document.getElementById('statRate').textContent=d.completion_rate+'%';document.getElementById('statWeek').textContent=d.weekly.reduce((s,x)=>s+Number(x.completed||0),0);
weeklyChart?.destroy();weeklyChart=new Chart(document.getElementById('weeklyChart'),{type:'bar',data:{labels:d.weekly.map(x=>x.label),datasets:[{label:'Completed',data:d.weekly.map(x=>Number(x.completed))}]},options:{responsive:true,scales:{y:{beginAtZero:true,ticks:{precision:0}}}}});
monthlyChart?.destroy();monthlyChart=new Chart(document.getElementById('monthlyChart'),{type:'line',data:{labels:d.monthly.map(x=>x.label),datasets:[{label:'Completed',data:d.monthly.map(x=>Number(x.completed)),tension:.3,fill:false}]},options:{responsive:true,scales:{y:{beginAtZero:true,ticks:{precision:0}}}}});
categoryChart?.destroy();categoryChart=new Chart(document.getElementById('categoryChart'),{type:'doughnut',data:{labels:d.categories.length?d.categories.map(x=>x.category):['No habits'],datasets:[{data:d.categories.length?d.categories.map(x=>Number(x.habits)):[1]}]},options:{responsive:true,plugins:{legend:{position:'bottom'}}}});
}loadAnalytics();
</script></body></html>
